# ISS ME DICTIONARY AUR DICTIONARY KE FUNCTIONS HONGE BAS YE HE .......

d1={}
# print(type(d1))
d2={"Harry":"Burger", "Rohan":"Fish", "SkillF":"Roti"}  # aapna dictionary ke andar dictionary bhi dal skte hai ..
print(d2)
print(d2["Harry"])  # iss se aapne ko uss ek value milti hai ye bhot kam ka hai .....

d2={"Harry":"Burger", "Rohan":"Fish", "SkillF":"Roti", "Shubham":{"B":"gandu ", "L":"roti", "D":"matti"}}


print(d2["Shubham"]["B"]) # ye aapan vo dictionary in a dictionary ka hai (iss me aapan dictionary in a dictionary bhi use kr skte hai ..)

d2["Sala"]="chickoo"
print(d2)
a=input()
